"$schema" = "node_modules/wrangler/config-schema.json"
name = "yunosuke-portfolio"
compatibility_date = "2026-03-17"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]
workers_dev = true

[observability]
enabled = true


[env.preview]
name = "yunosuke-portfolio-preview"
workers_dev = true
