// This file is auto-generated by TanStack Router

import { Route as rootRoute } from './routes/__root'
import { Route as PrivacyPolicyRoute } from './routes/privacy-policy'
import { Route as ContactRoute } from './routes/contact'
import { Route as IndexRoute } from './routes/index'
import { Route as ArticleIndexRoute } from './routes/article.index'
import { Route as ArticleSlugRoute } from './routes/article.$slug'
import { Route as ArticlePagePageRoute } from './routes/article.page.$page'

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    '/contact': {
      preLoaderRoute: typeof ContactRoute
      parentRoute: typeof rootRoute
    }
    '/privacy-policy': {
      preLoaderRoute: typeof PrivacyPolicyRoute
      parentRoute: typeof rootRoute
    }
    '/article': {
      preLoaderRoute: typeof ArticleIndexRoute
      parentRoute: typeof rootRoute
    }
    '/article/$slug': {
      preLoaderRoute: typeof ArticleSlugRoute
      parentRoute: typeof rootRoute
    }
    '/article/page/$page': {
      preLoaderRoute: typeof ArticlePagePageRoute
      parentRoute: typeof rootRoute
    }
  }
}

const IndexLazyRoute = IndexRoute
const ContactLazyRoute = ContactRoute
const PrivacyPolicyLazyRoute = PrivacyPolicyRoute
const ArticleIndexLazyRoute = ArticleIndexRoute
const ArticleSlugLazyRoute = ArticleSlugRoute
const ArticlePagePageLazyRoute = ArticlePagePageRoute

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  ContactLazyRoute,
  PrivacyPolicyLazyRoute,
  ArticleIndexLazyRoute,
  ArticleSlugLazyRoute,
  ArticlePagePageLazyRoute,
])
